"""SQL validation for the Brain module.

Provides a second layer of SQL safety checking on LLM-generated queries
before they are sent to the database engine. Complements the DB module's
sanitizer with Brain-specific checks.
"""

import re

from hex.shared.errors import WriteOperationDetected


# Write operations that should be immediately rejected (no retry)
_WRITE_PATTERN = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE)\b",
    re.IGNORECASE,
)


def check(sql: str) -> None:
    """Validate that LLM-generated SQL is safe for execution.

    Checks for write operations and basic syntax sanity. This is a
    Brain-level guard — the DB sanitizer provides a second layer.

    Args:
        sql: The SQL query string generated by the LLM.

    Raises:
        WriteOperationDetected: If the SQL contains write operations.
            This error is fatal — no retry should be attempted.
    """
    if not sql or not sql.strip():
        return  # None/empty SQL is handled upstream (means "can't answer")

    match = _WRITE_PATTERN.search(sql)
    if match:
        keyword = match.group(1).upper()
        raise WriteOperationDetected(
            f"LLM generated a {keyword} statement — blocked immediately"
        )
